(in-package :asteroids.entities)
(defclass boundary-behavior () ())
(defgeneric boundary-check (entity x-limit y-limit))

(defclass reset-behavior () ())
(defmethod boundary-check ((entity reset-behavior) x-limit y-limit)
  (when (< (sprite-x entity) 0)
    (setf (sprite-x entity) x-limit)
    (setf (box-x entity) (sprite-x entity)))
  (when (> (sprite-x entity) x-limit)
    (setf (sprite-x entity) 0)
    (setf (box-x entity) (sprite-x entity)))
  (when (< (sprite-y entity) 0)
    (setf (sprite-y entity) y-limit)
    (setf (box-y entity) (sprite-y entity)))
  (when (> (sprite-y entity) y-limit)
    (setf (sprite-y entity) 0)
    (setf (box-y entity) (sprite-y entity))))

(defclass kill-behavior () ())
(defmethod boundary-check ((entity kill-behavior) x-limit y-limit)
  (when (or (< (sprite-x entity) 0)
            (< (sprite-y entity) 0)
            (> (sprite-x entity) x-limit)
            (> (sprite-y entity) y-limit))
    (setf (sprite-x entity) 99999)
    (setf (box-x entity) 99999)
    (setf (magnitude (velocity entity)) 0)
    (setf (off-screen entity) t)))
