(in-package :asteroids.entities)
(defclass Entity (Sprite) nil)
(defgeneric update (Entity))
(defgeneric boundary-check (Entity x-limit y-limit))

(defmethod boundary-check ((entity entity) x-limit y-limit)
  (when (< (x entity) 0)
    (setf (x entity) x-limit))
  (when (> (x entity) x-limit)
    (setf (x entity) 0))
  (when (< (y entity) 0)
    (setf (y entity) y-limit))
  (when (> (y entity) y-limit)
    (setf (y entity) 0)))
